### ISSUE TITLE
I got Error

### ISSUE THREAD

**Issue by afsatechnical** [cre8oracademy/webbrute#1]
Traceback (most recent call last):
  File "c:\Users\91940\Desktop\webbrute-master\webbrute.py", line 13, in <module>
    url = str(raw_input("\033[1;34;40m Enter Url Of Login Page: \033[1;32;40m"))
NameError: name 'raw_input' is not defined

**Comment by jyotirmaya-bloghost** [comment]
File "c:\Users\Lenovo\Desktop\py-games\webbrute-master\webbrute.py", line 13, in <module>
    url = str(raw_input("\033[1;34;40m Enter Url Of Login Page:https://contentwriters.com/accounts/login \033[1;32;40m"))
NameError: name 'raw_input' is not defined

**Comment by saifullahsaeed** [comment]
use  python2
